// <auto-generated />
namespace PuntoFitness2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _bool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_bool));
        
        string IMigrationMetadata.Id
        {
            get { return "201507221758282_bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
